### PR TITLE
use pow() approximation for contrast

### PR DESCRIPTION
**Pull request by xi**
With this change, the contrast calculation would no longer depend on a `pow()` function. The approximation is really very good (the difference is never bigger than 0.005).

http://www.wolframalpha.com/input/?i=(133+*+x**3+%2B+155+*+x**2)+%2F+288,+x**2.4+from+0+to+1

### CODE REVIEW

**Comment by mirisuzanne** [comment]
Woah, that's very slick. I imagine we could use that on accoutrement-scale as well. I'll play with it, and get it merged later today. thanks!

**Comment by xi** [comment]
Unfortunately, the same thing can not be used in accoutrement-scale because you have to pre-calculate it for every exponent (in this case 2.4). It also only for bases between 0 and 1.

**Comment by xi** [comment]
I no longer think this is a good idea. I realised that the contrast formular amplifies input errors, so the small errors from this approximation result in signficant errors in the contrast values.

From this perspective, the approximation `0.56 * ($c * $c * $c) + 0.44 * ($c * $c)` is preferable. The contrast error with this one is below 1. However, I think this is still way too much.

If you are interested, I could implement this as a fallback if `not function-exists('pow')`.

**Comment by mirisuzanne** [comment]
@xi having it as a fallback sounds like a great solution! Thanks!

**Pull request closed without merging**
